module.exports = {
  HIGH_VALUE: 50000,
  RAPID_SUCCESSIVE: { count: 5, minutes: 10 },
  STRUCTURING_LIMIT: 10000,
  SMURFING_COUNT: 10,
  NEW_ACCOUNT_DAYS: 7,
  NEW_ACCOUNT_HIGH_VALUE: 20000,
  FREQUENT_SAME_ACCOUNTS: 5,
  UNUSUAL_HOURS: [0, 4],
  HIGH_RISK_COUNTRIES: ["XX", "YY", "ZZ"],
};
